export const API_URL = '/api/todos';

export const GET_LIST_START = 'TODOS_GET_LIST_START';
export const GET_LIST_SUCCESS = 'TODOS_GET_LIST_SUCCESS';
export const GET_LIST_ERROR = 'TODOS_GET_LIST_ERROR';

export const POST_ITEM_START = 'TODOS_POST_ITEM_START';
export const POST_ITEM_SUCCESS = 'TODOS_POST_ITEM_SUCCESS';
export const POST_ITEM_ERROR = 'TODOS_POST_ITEM_ERROR';
